"""
API endpoints for the Transaction (stg_subledger) resource.

Defines the HTTP routes for full CRUD operations against the Bronze-layer
staging table. Routes are intentionally thin: they validate input, delegate
to the service layer, and shape HTTP responses. All business logic lives in
the service and repository layers.
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.database.session import get_db
from app.schemas.transaction import (
    TransactionCreate,
    TransactionResponse,
    TransactionUpdate,
)
from app.services.transaction_service import TransactionService

router = APIRouter(prefix="/transactions", tags=["Transactions"])


@router.post(
    "",
    response_model=TransactionResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create a new transaction",
)
def create_transaction(
    payload: TransactionCreate,
    db: Session = Depends(get_db),
) -> TransactionResponse:
    """
    Insert a new raw transaction record into the Bronze staging table.

    The surrogate 'id' is generated by the database and returned in the
    response. Data is accepted as-is (raw), consistent with Bronze-layer
    ingestion.
    """
    service = TransactionService(db)
    transaction = service.create_transaction(payload)
    return transaction


@router.get(
    "",
    response_model=list[TransactionResponse],
    summary="List transactions",
)
def list_transactions(
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db),
) -> list[TransactionResponse]:
    """Retrieve a paginated list of transactions from the staging table."""
    service = TransactionService(db)
    return service.get_transactions(skip=skip, limit=limit)


@router.get(
    "/{transaction_id}",
    response_model=TransactionResponse,
    summary="Get a transaction by id",
)
def get_transaction(
    transaction_id: int,
    db: Session = Depends(get_db),
) -> TransactionResponse:
    """Retrieve a single transaction by its surrogate id."""
    service = TransactionService(db)
    transaction = service.get_transaction(transaction_id)
    if transaction is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Transaction with id {transaction_id} not found",
        )
    return transaction


@router.put(
    "/{transaction_id}",
    response_model=TransactionResponse,
    summary="Update a transaction",
)
def update_transaction(
    transaction_id: int,
    payload: TransactionUpdate,
    db: Session = Depends(get_db),
) -> TransactionResponse:
    """Update an existing transaction by id."""
    service = TransactionService(db)
    transaction = service.update_transaction(transaction_id, payload)
    if transaction is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Transaction with id {transaction_id} not found",
        )
    return transaction


@router.delete(
    "/{transaction_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a transaction",
)
def delete_transaction(
    transaction_id: int,
    db: Session = Depends(get_db),
) -> None:
    """Delete a transaction by id. Returns 204 on success, 404 if not found."""
    service = TransactionService(db)
    deleted = service.delete_transaction(transaction_id)
    if not deleted:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Transaction with id {transaction_id} not found",
        )